In [1]:
import numpy as np

from sklearn.cluster import DBSCAN
from sklearn import metrics
from sklearn.datasets.samples_generator import make_blobs
from sklearn.preprocessing import StandardScaler

import xlwings

In [2]:
#generate data
centers = [[1, 1], [-1, -1], [1, -1]]
X, labels_true = make_blobs(n_samples=750, centers=centers, cluster_std=0.4,
                            random_state=0)

X = StandardScaler().fit_transform(X)

In [3]:
X.shape

(750, 2)

In [4]:
#scikit learn expects each np row to be a record
#so an n by c matrix has n samples with c variables

X[0:1,:]

array([[0.49426097, 1.45106697]])

In [ ]:
db = DBSCAN(eps=0.3, min_samples=10).fit(X)
core_samples_mask = np.zeros_like(db.labels_, dtype=bool)
core_samples_mask[db.core_sample_indices_] = True
labels = db.labels_

# Number of clusters in labels, ignoring noise if present.
n_clusters_ = len(set(labels)) - (1 if -1 in labels else 0)
n_noise_ = list(labels).count(-1)

print('Estimated number of clusters: %d' % n_clusters_)
print('Estimated number of noise points: %d' % n_noise_)
print("Homogeneity: %0.3f" % metrics.homogeneity_score(labels_true, labels))
print("Completeness: %0.3f" % metrics.completeness_score(labels_true, labels))
print("V-measure: %0.3f" % metrics.v_measure_score(labels_true, labels))
print("Adjusted Rand Index: %0.3f"
      % metrics.adjusted_rand_score(labels_true, labels))
print("Adjusted Mutual Information: %0.3f"
      % metrics.adjusted_mutual_info_score(labels_true, labels))
print("Silhouette Coefficient: %0.3f"
      % metrics.silhouette_score(X, labels))


In [5]:
import cv2
im = cv2.imread(r'c:\development\python\EAST\test\bin\sa6.jpg')

In [11]:
hist=np.bincount(im.ravel(),minlength=256,normalize=True)

TypeError: 'normalize' is an invalid keyword argument for this function

In [8]:
hist.shape

(256,)

(26110044,)

In [12]:
print(np.bincount.__doc__)


    bincount(x, weights=None, minlength=0)

    Count number of occurrences of each value in array of non-negative ints.

    The number of bins (of size 1) is one larger than the largest value in
    `x`. If `minlength` is specified, there will be at least this number
    of bins in the output array (though it will be longer if necessary,
    depending on the contents of `x`).
    Each bin gives the number of occurrences of its index value in `x`.
    If `weights` is specified the input array is weighted by it, i.e. if a
    value ``n`` is found at position ``i``, ``out[n] += weight[i]`` instead
    of ``out[n] += 1``.

    Parameters
    ----------
    x : array_like, 1 dimension, nonnegative ints
        Input array.
    weights : array_like, optional
        Weights, array of the same shape as `x`.
    minlength : int, optional
        A minimum number of bins for the output array.

        .. versionadded:: 1.6.0

    Returns
    -------
    out : ndarray of ints
        The resu

In [2]:
import opencvlib.histo as histo
import cv2
im = cv2.imread(r'c:\development\python\EAST\test\bin\sa6.jpg')

In [3]:
out = histo.histo_hsv(im)

In [4]:
out.shape

(180, 255)

In [20]:
zz = im.copy()

In [9]:
imravel = np.ravel(im/255)

In [8]:
import numpy as np

In [10]:
np.bincount(imravel, minlength=10)

TypeError: Cannot cast array data from dtype('float64') to dtype('int64') according to the rule 'safe'

In [11]:
from fast_histogram import histogram1d

In [14]:
histogram1d(imravel, range=[0, 1], bins=10)

array([ 633440.,  819712.,  520066.,  365484., 1405992., 2854046.,
       4301443., 2203134., 1268503., 7773555.])

In [15]:
print(np.linspace.__doc__)


    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    retstep : bool, optional
        If True, return (`samples`, 

In [18]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [19]:
im.shape

(3508, 2481, 3)

In [22]:
a=np.array([1,2,3])
def f(a):
    b=np.array([5,6,7])
    a = b
f(a)
print(a)

[1 2 3]


In [23]:
a=1
a /= 0.5

In [30]:
img = np.random.randint(0, 256, (255, 255, 3))

In [27]:
img = np.ones((255, 255, 3))

In [33]:
np.max(img)

255

In [35]:
import plotlib.matplotlib_2d as mpl2

ImportError: No module named 'config'

In [36]:
def a():
    return [1,2,3]


e,r,t=a()

In [37]:
e

1

In [38]:
a=[1,2,3,4]
a[0:len(a)-1]

[1, 2, 3]