In [71]:
from warnings import warn as _warn
import numpy as _np
import cv2 as _cv2
import scipy.ndimage as _ndimage
import scipy.spatial.distance as _dist

In [ ]:
def feature_dist(input):
    """
    Takes a labeled array as returned by scipy.ndimage.label and 
    returns an intra-feature distance matrix.
    """
    if isinstance(labelled_array, tuple):
        _warn('Tuple was passed to feature_dist, assuming the ndarray is in the tuple. This happens of the output from ndimage.label is used directly and is not a problem.')
        labelled_array = labelled_array[0]

    I, J = _np.nonzero(input)
    labels = input[I,J]
    coords = _np.column_stack((I,J))

    sorter = _np.argsort(labels)
    labels = labels[sorter]
    coords = coords[sorter]

    sq_dists = _dist.cdist(coords, coords, 'sqeuclidean')

    start_idx = _np.flatnonzero(_np.r_[1, _np.diff(labels)])
    nonzero_vs_feat = _np.minimum.reduceat(sq_dists, start_idx, axis=1)
    feat_vs_feat = _np.minimum.reduceat(nonzero_vs_feat, start_idx, axis=0)

    return _np.sqrt(feat_vs_feat)

In [76]:
A = _np.zeros(100).reshape(10,10)
A[:,0:6] = 1
A[0,9]=2
A[8:10,8:10]=3
ALbl= _ndimage.label(A)[0]
print(ALbl)

AL

[[1 1 1 1 1 1 0 0 0 2]
 [1 1 1 1 1 1 0 0 0 0]
 [1 1 1 1 1 1 0 0 0 0]
 [1 1 1 1 1 1 0 0 0 0]
 [1 1 1 1 1 1 0 0 0 0]
 [1 1 1 1 1 1 0 0 0 0]
 [1 1 1 1 1 1 0 0 0 0]
 [1 1 1 1 1 1 0 0 0 0]
 [1 1 1 1 1 1 0 0 3 3]
 [1 1 1 1 1 1 0 0 3 3]]


In [77]:
feature_dist(ALbl)

array([[0., 4., 3.],
       [4., 0., 8.],
       [3., 8., 0.]])

In [78]:
C = _np.array([[[2243, 3363]],

       [[2242, 3364]],

       [[2242, 3392]],

       [[2243, 3392]],

       [[2244, 3393]],

       [[2302, 3393]],

       [[2303, 3392]],

       [[2303, 3364]],

       [[2302, 3363]]], dtype='int32')

In [79]:
cntrs = [C,C,C]
def contour_to_cvpts(cnt):
    '''(n,1,2-ndarray) -> n,2-list
    Convert a contour points to
    standard CVXY points list.

    cnt:A cv2 contour, which is an n,1,2 ndarray

    Returns:
    List of points in standard cv format, e.g. [[0,0],[1,2]]
    '''
    return cnt.squeeze().tolist()


def contours_bounding_rect(contours):
    '''(list:n,1,2-ndarray)->y1, y2, x1, x2

    Returns:
        y1, y2, x1, x2. Chosen for ease of use in using for slicing
    '''
    allpts = []
    for c in contours:
        pts = contour_to_cvpts(c)
        _ = [allpts.append(pt) for pt in pts]
    xs, ys = zip(*allpts)
    return min(ys), max(ys), min(xs), max(xs)

In [80]:
contours_bounding_rect(cntrs)

(3363, 3393, 2242, 2303)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [85]:
ALbl.dtype

dtype('int32')

In [87]:
Z = _np.zeros((3400, 2500), dtype='int32')

In [93]:
I = _cv2.drawContours(Z, C, -1, 255)

In [94]:
I.shape

(3400, 2500)

In [97]:
T=_np.arange(9).reshape(3,3)

In [99]:
for r in T:
    for x in r:
        print(x)

0
1
2
3
4
5
6
7
8


In [100]:
l = [1,2,3]

In [ ]:
l[